### ISSUE TITLE
There is a bug

### ISSUE THREAD

**Issue by Fedon98** [Fedon98/soutenance-git-gp4#3]
**Describe the bug**
Bug assez complexe à fix

**To Reproduce**
1. Go to positiveNum.js

**Expected behavior**
Voir si le nombre est positif ou non

**Comment by grdnvictor** [comment]
On travaille dessus, la prochaine fois explique comment reproduire ton bug !

**Comment by Fedon98** [comment]
Bug résolu c'est super!
